### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by shanev13** [wiscostret/fplscrapR#1]
Hi,
I am new to R, so please forgive if this is a silly question.
Having problems installing fplscrapR. See below.
Please help?

> install.packages("fplscrapr")
Installing package into ‘C:/Users/Shane/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘fplscrapr’ is not available (for R version 3.3.3)
> library(fplscrapr)

> if (!require(remotes)) {
+   install.packages("remotes") 
+ }
Loading required package: remotes
> remotes::install_github("wiscostret/fplscrapR")
Downloading GitHub repo wiscostret/fplscrapR@master
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot download all files
> library(fplscrapR)
Error in library(fplscrapR) : there is no package called ‘fplscrapR’

``

**Comment by wiscostret** [comment]
Hi, apologies for the late reply. This seems like a utils problem, not an fplscrapR problem, as the error message indicates. Take a look here: https://github.com/forestgeo/learn/issues/102
