### ISSUE TITLE
Is not working anymore?

### ISSUE THREAD

**Issue by ejlamarque** [wiscostret/fplscrapR#14]
I found that it is not working anymore and try to reinstall but there is a problem and I can't. Any news?

**Comment by wiscostret** [comment]
Hi, could you expand on this? Just been testing out the functions and it seems to work fine here.

The easiest way to get help is to provide a [reproducible example](https://www.tidyverse.org/help/).

**Comment by ejlamarque** [comment]
Hi. Thank you for your prompt replay and sorry for the poor information. I manage to fix the problem. It was some dependency pack that after upgrade R Studio needs to be upgraded as well. Thank you again.
