### ISSUE TITLE
R Version 4.0.2

### ISSUE THREAD

**Issue by opdeclan** [wiscostret/fplscrapR#19]
Hello,

Not sure if this is the best place to ask, but I'm getting this error:

_package ‘fplscrapR’ is not available (for R version 4.0.2)_

What R version is needed to install fplscrapR?

**Comment by wiscostret** [comment]
Hi, this is a [good guide](https://stackoverflow.com/questions/25721884/how-should-i-deal-with-package-xxx-is-not-available-for-r-version-x-y-z-wa) to answer your question.

I haven´t checked the very-latest R version (4.0.2) - it was only released last month - but it´s likely one of the package ´depends´ are not available or incompatible with the latest release. I suggest as a temporary fix you install R 4.0.0, where the package should work fine. Let me know any other issues.
