### ISSUE TITLE
Error installing fplscrapR

### ISSUE THREAD

**Issue by MWilcock95** [wiscostret/fplscrapR#2]
I run the code and get the following screen:

> library(remotes)
> install_github("wiscostret/fplscrapR")
Downloading GitHub repo wiscostret/fplscrapR@master
These packages have more recent versions available.
Which would you like to update?

>1: All                             
2: CRAN packages only              
3: None                            
4: dplyr  (0.8.2  -> 0.8.3 ) [CRAN]
5: vctrs  (0.1.0  -> 0.2.0 ) [CRAN]
6: digest (0.6.19 -> 0.6.20) [CRAN]

>Enter one or more numbers, or an empty line to skip updates:
1
dplyr    (0.8.2  -> 0.8.3  ) [CRAN]
vctrs    (0.1.0  -> 0.2.0  ) [CRAN]
ellipsis (NA     -> 0.2.0.1) [CRAN]
digest   (0.6.19 -> 0.6.20 ) [CRAN]

I select the option to update all (although I receive an error for each option) and it successfully updates the packages

>package ‘dplyr’ successfully unpacked and MD5 sums checked
package ‘vctrs’ successfully unpacked and MD5 sums checked
package ‘ellipsis’ successfully unpacked and MD5 sums checked
package ‘digest’ successfully unpacked and MD5 sums checked

I then get the following issue related to fplscrapR

>Installing package into ‘C:/Users/Matt/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
> *installing *source* package 'fplscrapR' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in open.connection(con, "rb") : HTTP error 403.
Error: unable to load R code in package 'fplscrapR'
Execution halted
ERROR: lazy loading failed for package 'fplscrapR'
> *removing 'C:/Users/Matt/Documents/R/win-library/3.6/fplscrapR'
Error: Failed to install 'fplscrapR' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Matt/AppData/Local/Temp/RtmpCqCqmP/file1fcc67a878db/fplscrapR_0.1.0.tar.gz’ had non-zero exit status

I'm assuming this means that for whatever reason I don't have access and that it may be an issue on my end regarding the network but I can't figure out what that might be, figured I'd check this isn't a github or fplscrapR related error

**Comment by wiscostret** [comment]
Thanks for logging the issue here. It was indeed a network connection issue, but one caused by my hurry to update the package in response to the FPL API restructure, leaving a small bit of outdated code in the package. It should now work. Let me know if it doesn't.
