### ISSUE TITLE
Can't get_player_details of 20/21

### ISSUE THREAD

**Issue by maomontes** [wiscostret/fplscrapR#22]
Hi
Today I was trying to get player details from last season but this error appears
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'https://raw.githubusercontent.com/wiscostret/histfpldata/master/getplayerdetails20.csv': HTTP status was '404 Not Found'

**Comment by wiscostret** [comment]
It should work now - I hadn't uploaded the 20/21 season info to the repository, but I have done so now.

**Comment by maomontes** [comment]
Thx!!!!

**Comment by pme1301** [comment]
Hi, is the current season going to be uploaded?

Thanks.

**Comment by wiscostret** [comment]
> Hi, is the current season going to be uploaded?
> 
> Thanks.

All current season data is pulled directly from the FPL API with the function commands - do not use the ‘season’ parameter here (as it’s only for historical season). Simply run get_player_details()

**Comment by pme1301** [comment]
> > Hi, is the current season going to be uploaded?
> > Thanks.
> 
> All current season data is pulled directly from the FPL API with the function commands - do not use the ‘season’ parameter here (as it’s only for historical season). Simply run get_player_details()

Great thanks!
