### ISSUE TITLE
get_player_details error

### ISSUE THREAD

**Issue by ArnieWNZ** [wiscostret/fplscrapR#23]
I tried running get_player_details(name="Mohamed Salah") in R and I'm receiving the following error.
Error in open.connection(con, "rb") : cannot open the connection
In addition: Warning message:
In open.connection(con, "rb") :
  InternetOpenUrl failed: 'The operation timed out'

**Comment by wiscostret** [comment]
Hi, looks like a simple connection error - either on your end or the FPL API. If it's the former, you'll have to check your local connection. It could be the latter - the FPL API has been overloaded to start the season - then simply try another time.
