### ISSUE TITLE
Last Years Data

### ISSUE THREAD

**Issue by jonc92** [wiscostret/fplscrapR#3]
Hiya,

I built a few things in March/April time using last years (2018-19) data. Is there any way of accessing the old data with fplscrapR? 

Been enjoying using the tool though, thanks!

**Comment by wiscostret** [comment]
I am currently working on an update to fplscrapR, which will include access to prior season's date in the functions. It will be available as soon as the new season is live. In the meantime if you need this data, it is available in this repo: https://github.com/wiscostret/histfpldata
