### ISSUE TITLE
get_player_hist is not working 

### ISSUE THREAD

**Issue by pradhann** [wiscostret/fplscrapR#4]
get_player_hist results in a parsing error. 

The error can be fixed by removing url in

fplboot <- jsonlite::fromJSON(**_url_**(paste("https://fantasy.premierleague.com/api/element-summary/",elements$id[i],sep="")))$history_past

**Comment by wiscostret** [comment]
Thanks for the note. the url command shouldn't make difference, perhaps there was an issue with the restructure API at the moment.

If you are still experiencing the issue, please produce a minimum reproducible example.

**Comment by wiscostret** [comment]
Issue no longer relevant given package updates. Please open a new issue with a reprex if the issue persists.
