### ISSUE TITLE
Get Games List

### ISSUE THREAD

**Issue by theparttimeanalyst** [wiscostret/fplscrapR#7]
Hi There, 

Great package, the get_game_listfunction only seems to work for season 18/19. Not current season or any of the previous seasons 

Cheers

**Comment by wiscostret** [comment]
Thanks! To answer your question: At the moment, the function can pull data from the current season and 18/19. To grab the data for the current season, don't specify anything for the 'season' parameter. Just call 'get_game_list()'. For the 18/19 data, call 'get_game_list(season=18)'.

To elaborate: this is how all the 'season' parameters work throughout the package functions. It was a design choice for the v0.2 update: it allows me to update the package with future season's data without needed to change the functions. However, with early feedback I can see it is not ideal design, as when to use/not use the 'season' parameter is not intuitive. It'll be on the list of things to consider for the next package update.
