### ISSUE TITLE
Install package

### ISSUE THREAD

**Issue by davidmcbey** [wiscostret/fplscrapR#9]
I've tried to install fplscrapR using RStudio 1.2.5001 and get the following error message:

> install.packages("fplscrapR")
Warning in install.packages :
  package ‘fplscrapR’ is not available (for R version 3.6.1)

Any help appreciated!

**Comment by davidmcbey** [comment]
nvm - I managed to fix it using this [guide](https://www.datacamp.com/community/tutorials/r-packages-guide) and dev tools

**Comment by wiscostret** [comment]
Oh that's great, thank you. Would you mind sharing the exact steps of your solution, in case anyone else runs into the same problem?

**Comment by davidmcbey** [comment]
Sure, I think the problem was I wasn't searching for fplscrapR in the correct repository i.e. here on GitHub.

I started by installing Devtools to make it easier to install packages from different repositories:

install.packages("devtools")

Then, I used to devtools to pull fplscrapR from here:

devtools::install_github("wiscostret/fplscrapR")
